# Generated by Django 3.0.5 on 2021-10-11 22:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('age', models.CharField(default='', max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('rstatus', models.CharField(default='', max_length=60)),
                ('rbackground', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'BT Info(Personal Rabbi)',
            },
        ),
        migrations.CreateModel(
            name='BTone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics/')),
                ('job', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'BT One',
            },
        ),
        migrations.CreateModel(
            name='BTOnePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics/')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000000)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'BT One Posts',
            },
        ),
        migrations.CreateModel(
            name='BTthree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics/')),
                ('job', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'BT Three',
            },
        ),
        migrations.CreateModel(
            name='BTThreePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000000)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'BT Three Posts',
            },
        ),
        migrations.CreateModel(
            name='BTtwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics/')),
                ('job', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'BT Two',
            },
        ),
        migrations.CreateModel(
            name='BTTwoPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000000)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'BT Two Posts',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Kiruv', 'kiruv'), ('Synagogues', 'synagogues'), ('Calendars', 'calendars'), ('Campus Life', 'campus life'), ('Death and Bereavment', 'death and bereavment')], max_length=60)),
                ('namesub', models.CharField(default='Empty', max_length=60)),
                ('link', models.URLField(default='No Link')),
                ('submenu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Community',
            },
        ),
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Shiurim', 'shiurim'), ('1-on-1 Connections', '1-on-1 connections'), ('Mailing List', 'mailing list')], max_length=60)),
                ('namesub', models.CharField(default='Empty', max_length=60)),
                ('link', models.URLField(default='No Link')),
                ('submenu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Learning',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100000)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Useful Phone Apps', 'useful phone apps'), ('Connect With Family', 'connect with family'), ('Blogs', 'blogs')], max_length=60)),
                ('namesub', models.CharField(default='Empty', max_length=60)),
                ('link', models.URLField(default='No Link')),
                ('submenu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Technology',
            },
        ),
        migrations.CreateModel(
            name='Thebig5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Shabbat', 'shabbat'), ('Davening', 'davening'), ('Kashrus', 'kashrus'), ('Tefillin', 'tefillin'), ('Taharas Mishpacha', 'taharas mishpacha')], max_length=60)),
                ('namesub', models.CharField(default='Empty', max_length=60)),
                ('link', models.URLField(default='No Link')),
                ('submenu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'The Big 5',
            },
        ),
        migrations.CreateModel(
            name='SublinkTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subItems', models.CharField(default='Empty', max_length=60)),
                ('link', models.URLField(default='No Link')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baaleit.Technology')),
            ],
            options={
                'verbose_name_plural': 'Sub-link Technology',
            },
        ),
        migrations.CreateModel(
            name='SublinkLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subItems', models.CharField(default='Empty', max_length=60)),
                ('link', models.URLField(default='No Link')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baaleit.Learning')),
            ],
            options={
                'verbose_name_plural': 'Sub-link Learning',
            },
        ),
        migrations.CreateModel(
            name='SublinkCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subItems', models.CharField(default='Empty', max_length=60)),
                ('link', models.URLField(default='No Link')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baaleit.Community')),
            ],
            options={
                'verbose_name_plural': 'Sub-link Community',
            },
        ),
        migrations.CreateModel(
            name='Sublink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subItems', models.CharField(default='Empty', max_length=60)),
                ('link', models.URLField(default='No Link')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baaleit.Thebig5')),
            ],
            options={
                'verbose_name_plural': 'Sub-link',
            },
        ),
    ]
