# Generated by Django 3.0.5 on 2021-10-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baaleit', '0002_remove_btonepost_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='btonepost',
            name='img',
            field=models.ImageField(default='C:\\DjangoStuff\x08aaleiteshuva\x08aaleit\\static\x07ssets\\img\reading.png', upload_to='pics/'),
        ),
    ]
