# Generated by Django 3.0.5 on 2021-10-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baaleit', '0002_auto_20210924_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='bt',
            name='rstatus',
            field=models.CharField(default='', max_length=60),
        ),
    ]
